name: CI-Staging

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - staging

jobs:
  staging:
    runs-on: ubuntu-latest
    env:
      REMOTE: ${{ github.event.pull_request.head.repo.clone_url }}
      ORIGEN: ${{ github.event.pull_request.head.ref }}
      DESTINO: ${{ github.event.pull_request.base.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Validar que el PR ya pas√≥ por ambiente previo
        if: ${{ github.event_name == 'pull_request' }}
        env:
          REMOTE: ${{ github.event.pull_request.head.repo.clone_url }}
          ORIGEN: ${{ github.event.pull_request.head.ref }}
          DESTINO: ${{ github.event.pull_request.base.ref }}
        run: |
          git fetch origin release
          LAST_COMMIT=$(git rev-parse origin/${GITHUB_HEAD_REF})
    
          COMMON_ANCESTOR=$(git merge-base origin/release $LAST_COMMIT)
          if [ "$COMMON_ANCESTOR" != "$LAST_COMMIT" ]; then
            echo "Los cambios de la rama ${GITHUB_HEAD_REF} deben haber sido integrados previamente en la rama release"
            exit 1
          fi

      - name: Re-run last check
        if: github.event.pull_request.merged == true
        env:
          OWNER: JhonJimenezCastro
          REPO: testrepositor
          ORIGEN: ${{ github.event.pull_request.head.ref }}
          DESTINO: "main"
          TOKEN: ${{ secrets.TOKEN }}
        run: |  
            pr_url=$(curl -s \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer $TOKEN" \
              https://api.github.com/repos/${OWNER}/${REPO}/pulls?state=open | \
              jq -r '.[] | select(.head.ref=="'$ORIGEN'" and .base.ref=="'$DESTINO'") | .url')
  
            pr_sha=$(curl -s \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer $TOKEN" \
              $pr_url | jq -r '.head.sha')
            echo "SHA $pr_sha"
  
            run_ids=$(curl -s \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer $TOKEN" \
              https://api.github.com/repos/${OWNER}/${REPO}/actions/runs \
              | jq -r '.workflow_runs[] | select(.head_sha == "'$pr_sha'" ) | .id')
  
            for run_id in $run_ids
            do
              if [ -z "$run_id" ] || [ "$run_id" == "null" ]
              then
                echo "No se encontraron runs para el PR $pr_url"
              else
                rerun=$(curl -s \
                  -X POST \
                  -H "Accept: application/vnd.github.v3+json" \
                  -H "Authorization: Bearer $TOKEN" \
                  https://api.github.com/repos/${OWNER}/${REPO}/actions/runs/$run_id/rerun)
              fi        
            done
